# Generated by Django 3.0.3 on 2020-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200216_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='new arrivals', max_length=100, verbose_name='тэг'),
        ),
    ]
