# Generated by Django 3.0.3 on 2020-02-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
