# Generated by Django 3.0.3 on 2020-02-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_icon_iconcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='text',
            field=models.TextField(blank=True, verbose_name='значение'),
        ),
    ]
